Add filter for post types
xwp/multisite-search pull request #3
Opened 2020-04-11 14:31 UTC by edmundcwm

Add filter for excluding specific post types from search.

2020-04-15 04:41 UTC, rheinardkorf commented
@edmundcwm , it would be ideal to not have the posts get indexed in the first place.  Apply a filter like `skipped_posts` here: https://github.com/xwp/multisite-search/blob/master/php/Admin/class-index.php#L32

The root cause of the problem is here: https://github.com/xwp/multisite-search/blob/master/php/Hooks/class-post-type.php#L44

Even though it defaults to `page` and `post`, this function will index ANYTHING.

2020-04-15 04:42 UTC, rheinardkorf commented
A seperate issue, the code in https://github.com/xwp/multisite-search/blob/master/php/CLI/class-index.php#L30 will ONLY index `post` and `page`.  This would need to be fixed to include other types. 

Recommend this as a seperate issue.

2020-04-15 04:49 UTC, rheinardkorf requested changes

2020-04-15 04:49 UTC, rheinardkorf commented on php/Utility/class-search.php
> +		// List of post types to exclude from search.
See other comments on the PR to avoid requiring this code in the first place.

2020-04-29 12:10 UTC, edmundcwm commented
PR edited!

2020-05-14 04:43 UTC, merged